{{- if include "scramdb.createLicenseSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scramdb.licenseSecretName" . }}
  namespace: {{ include "scramdb.namespace" . }}
  labels:
    {{- include "scramdb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.license.secretKeys.licenseKey }}: {{ .Values.license.key | b64enc | quote }}
{{- end }}
